name: 夸克网盘每日签到

on:
  schedule:
  
    - cron: '1 12 * * *'

    - cron: '18 22 * * *'   # UTC 0:30 = 北京时间 6：18
  workflow_dispatch:       # 手动触发按钮

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: npm install axios

      - name: 运行签到
        run: node checkin.js
        env:
          TZ: Asia/Shanghai
          COOKIE_QUARK: ${{ secrets.COOKIE_QUARK }}
          DD_ACCESS_TOKEN: ${{ secrets.DD_ACCESS_TOKEN }}
          DD_SECRET: ${{ secrets.DD_SECRET }}
